server:
  port: ${SERVER_PORT:8081}
  forward-headers-strategy: framework

spring:
  application:
    name: warehouse

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5436/warehouse}
    username: ${DB_USERNAME:warehouse_user}
    password: ${DB_PASSWORD:warehouse_pswd}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        # Таблицы созданы Liquibase в схеме ms_warehouse, поэтому Hibernate тоже должен работать в этой схеме.
        default_schema: ms_warehouse

  liquibase:
    enabled: true
    change-log: classpath:db/database_ms_warehouse-changelog.xml
    default-schema: ms_warehouse
    drop-first: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}

# настройки Feign/HTTP-клиента (не обязательно, но удобно)
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 5000
            loggerLevel: BASIC
      compression:
        request:
          enabled: true
          mime-types: application/json
        response:
          enabled: true

feign:
  httpclient:
    enabled: true
  okhttp:
    enabled: false

customer:
  url: ${CLIENT_URL:http://localhost:8083}

logging:
  level:
    org.springframework.boot.context.config: debug
    liquibase: debug
    org.springframework.security: debug

kafka:
  topic: cargo-topic

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}